Text(
    text='',  # 显示的文本内容
    position=(0, 0),  # 屏幕位置 (x, y)，基于像素坐标
    origin=(0, 0),  # 原点位置，控制对齐方式
    z=-0.1,  # 深度值，影响渲染顺序
    color=color.white,  # 文本颜色
    enabled=True,  # 是否启用
    eternal=False,  # 是否永久存在（不随场景销毁）
    font=builtins.print,  # 字体对象或字体名称
    resolution=24,  # 字体分辨率
    size=0.025,  # 文本大小
    wordwrap=0,  # 自动换行宽度（0表示不换行）
    language='en',  # 语言设置
    parent=camera.ui,  # 父对象
    ignore=False,  # 是否忽略更新
    ignore_paused=False,  # 暂停时是否忽略
    always_on_top=False,  # 是否始终显示在最上层
    shader=None,  # 着色器
    visible=True,  # 是否可见
    clip_to_bounds=False,  # 是否裁剪到边界
    render_queue=0,  # 渲染队列
    billboard=False,  # 是否使用公告牌效果
    model='quad',  # 使用的模型
    collider='box',  # 碰撞体类型
    highlight_color=color.white,  # 高亮颜色
    pressed_color=color.white,  # 按下时的颜色
    scale=1,  # 缩放比例
    scale_x=1,  # X轴缩放
    scale_y=1,  # Y轴缩放
    rotation=(0, 0, 0),  # 旋转角度 (x, y, z)
    world_rotation=(0, 0, 0),  # 世界坐标系下的旋转
    texture=None,  # 纹理
    texture_scale=1,  # 纹理缩放
    texture_offset=(0, 0),  # 纹理偏移
    add_to_scene_entities=True,  # 是否添加到场景实体列表
    on_click=None,  # 点击回调函数
    on_mouse_enter=None,  # 鼠标进入回调函数
    on_mouse_exit=None,  # 鼠标离开回调函数
    line_height=1.5,  # 行高
    drop_shadow=(0, 0),  # 阴影偏移 (x, y)
    drop_shadow_color=color.black,  # 阴影颜色
    background=False,  # 是否显示背景
    background_color=color.black66,  # 背景颜色
    background_padding=0,  # 背景内边距
    border=False,  # 是否显示边框
    border_color=color.white,  # 边框颜色
    border_width=0,  # 边框宽度
    radius=0,  # 圆角半径
    **kwargs  # 其他关键字参数
)